---
nvm_version: 0.39.3
# nvm_version: 'master'
# nvm_version: 'latest'
# nvm_version: 'HEAD'

nvm_node_version: 18.16.0
# nvm_node_version: 'lts'
# nvm_node_version: 'latest'

# path config
nvm_install_path: ~/.nvm
nvm_shell_init_file: ~/.profile

# force rewrite nvm folder from remove git
nvm_force_install: false

# allow to skip dependencies installation (for non-root user)
nvm_install_deps: true

# allow to change git url for use proxy
nvm_git_repository: https://github.com/creationix/nvm.git
